-- MySQL Script generated by MySQL Workbench
-- Sat Jun 25 04:10:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `url_avatar` TEXT NULL,
  `fonction` VARCHAR(45) NULL,
  `telephone` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  `droits` VARCHAR(5) NULL,
  `userDescription` TEXT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`CE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CE` (
  `idCE` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `idUser` INT NOT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idCE`),
  CONSTRAINT `fk_CE_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(60) NULL,
  `contenu` TEXT NULL,
  `dateCreation` TIMESTAMP NULL,
  `dateDernierEdit` TIMESTAMP NULL,
  `lockStatus` TINYINT NULL,
  `url_image` TEXT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idPost`),
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commentaires` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commentaires` (
  `idCommentaire` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NULL,
  `dateCreation` TIMESTAMP NULL,
  `dateDernierEdit` TIMESTAMP NULL,
  `lockStatus` TINYINT NULL,
  `idPost` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCommentaire`),
  CONSTRAINT `fk_Commetaires_posts`
    FOREIGN KEY (`idPost`)
    REFERENCES `mydb`.`posts` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commetaires_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`liker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`liker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`liker` (
  `idUser` INT NOT NULL,
  `idCommentaire` INT NOT NULL,
  `valeur` TINYINT NULL,
  PRIMARY KEY (`idUser`, `idCommentaire`),
  CONSTRAINT `fk_users_has_Commetaires_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_Commetaires_Commetaires1`
    FOREIGN KEY (`idCommentaire`)
    REFERENCES `mydb`.`Commentaires` (`idCommentaire`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`aimer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aimer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aimer` (
  `idUser` INT NOT NULL,
  `idPost` INT NOT NULL,
  `valeur` TINYINT NULL,
  PRIMARY KEY (`idUser`, `idPost`),
  CONSTRAINT `fk_users_has_posts_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_posts_posts1`
    FOREIGN KEY (`idPost`)
    REFERENCES `mydb`.`posts` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
